server:
  port: 8081

spring:
  application:
    name: funding-service
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/funding?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://mysql-container:3306/funding?useSSL=false&serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
  cloud:
    openfeign:
      httpclient:
        enabled: true
        connection-timeout: 5000 # ?? ?? ? ?? ?? ??? 5? ?? ? connection-time out ??
        ok-http:
          read-timeout: 5000 # ?? ???? ?? ??? 5? ?? ? read-time out ??

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 10
  client:
    serviceUrl:
      defaultZone: http://eureka-container:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.hibernate.SQL: debug

